import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavLinks } from '@/app/ui/partials/nav-links'
import Footer from "./ui/partials/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teste App",
  description: "Generated by 3Devs",
  icons: "./favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavLinks />
        {children}
        <Footer />
      </body>
    </html>
  );
}
